Fix unpublished images
ONSdigital/dp-download-service pull request #64
Opened 2020-12-24 12:49 UTC by jessjenkins

### What

- Support image downloading
- update to go 1.15
- fix dependency conflict with newer identity client and dp-net
- Update README and Swagger
- Support `ENCRYPTION_DISABLED=true`

### How to review

Ensure unit tests pass and code as expected.
The code should support ENCRYPTION_DISABLED=true for easier local development and testing. If using encryption, vault needs to be setup with a valid local config (v1 of kv secrets engine needs to be used which is not the default on newer versions of vault).

NB. There will be an accompanying PR for `dp-configs` to set `ENCRYPTION_DISABLED=false` in develop and prod, though this is the default in any case.

### Who can review

Anyone but me

2020-12-24 13:01 UTC, jessjenkins commented
Secrets PR… https://github.com/ONSdigital/dp-configs/pull/231

2020-12-29 11:48 UTC, DavidSubiros reviewed
Code looks good and unit tests pass. 

- Checked that we only call `GetWithPSK` if encryption is enabled and `Get` if encryption is disabled. Consistent with client creation.

- Validated that `ENCRYPTION_DISABLED` is false by default (encryption enabled by default)

- when we create the StreamWriter, we pass the value of VaultPath from config:
```
s3c := content.NewStreamWriter(s3, vc, cfg.VaultPath, cfg.EncryptionDisabled)
```
I see that the vaultPath format changed to start with `/`. Do we need to update the default value and secret?

2020-12-31 10:35 UTC, jessjenkins commented
> I see that the vaultPath format changed to start with `/`. Do we need to update the default value and secret?

So, I had a lot of indecision about this one. The final vault path itself doesn't start with a slash but the subpath does. Previously these were joined in the stream_writer as `vp := s.VaultPath + "/" + filepath.Base(filename)` but this was making the assumption that the vault path was always the filename which is only correct for datasets and filters. So I changed where the slash got added but ensured the end result was identical. 
Now for images, the vault sub-path is exactly the same as the s3 object key. The S3 object key should strictly have no slash prefix but unfortunately we do use a slash prefix for s3 for datasets and filters already.
Ideally I would like to make the s3path and vault path both without leading slashes but this would change (albeit correctly) the behaviour of the datasets and filters. Something I was trying to avoid. I am tempted to do it though as it is actually more correct, I just need to test it well.

As to your question, no we do not need to amend any secrets as the Vault path itself hasn't changed, only the sub-path which is internal to the service and not exposed.

2021-01-08 14:28 UTC, jessjenkins commented
I have updated the vault and s3 paths to now remove the leading slash. This is now the correct behaviour as s3 paths (or more correctly "keys") should not be prefixed with a leading slash.

2021-01-08 14:36 UTC, nshumoogum requested changes

2021-01-08 14:36 UTC, nshumoogum commented on downloads/downloader.go
> +	path = strings.TrimLeft(url.Path, "/") // TODO remove leading slash
TODO comment can be removed

2021-01-08 14:38 UTC, jessjenkins commented on downloads/downloader.go
> +	path = strings.TrimLeft(url.Path, "/") // TODO remove leading slash
🤦

2021-01-08 14:41 UTC, nshumoogum submitted a review, later dismissed

2021-01-08 14:55 UTC, nshumoogum submitted a review, later dismissed

2021-01-08 16:51 UTC, nshumoogum approved these changes

2021-01-08 17:15 UTC, merged